name: mobx_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  clippy_flutter: ^1.1.1
  cupertino_icons: ^1.0.2
  flutter_mobx: ^1.1.0+2
  flutter_native_splash: ^1.1.8+4
  get_it: ^6.0.0
  intl: ^0.17.0
  mobx_codegen: ^1.1.2
  numberpicker: ^2.0.1
  shared_preferences: ^2.0.5

dev_dependencies:
  build_runner: ^1.11.0

flutter_native_splash:
  color: "#EECD19"
#  background_image: "assets/images/launch_and_splash_screen/launch.png"
  image: "assets/images/launch_and_splash_screen/launch.png"
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/produtos/
    - assets/images/home/
    - assets/images/launch_and_splash_screen/